# Generated by Django 3.1.7 on 2021-06-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=80)),
                ('link', models.CharField(max_length=200)),
                ('imgsrc', models.CharField(max_length=200)),
            ],
        ),
    ]
